name: lefthook_dart
description: wrapper of lefthook for flutter and dart
version: 0.0.1
homepage: https://github.com/drt-pkgz/lefthook
environment:
  sdk: '>=3.8.0 <4.0.0'
executables:
  lefthook_dart: lefthook-dart
dependencies:
  archive: ^4.0.7
  system_info2: ^4.0.0
  cli_util: ^0.4.2
